# Generated by Django 4.0.2 on 2022-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supertypes',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
