# Generated by Django 4.0.2 on 2022-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='alter_ego',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='super',
            name='catchphrase',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='super',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='super',
            name='secondary_ability',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
