# Generated by Django 4.0.2 on 2022-02-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_alter_super_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
